### ISSUE TITLE
Feature : Support Nomad Task API

### ISSUE THREAD

**Issue by henrikjohansen** [ituoga/coredns-nomad#3]
Nomad's Task API provides every task managed by Nomad with a Unix Domain Socket (UDS) to access the local agent's HTTP  API. Regardless of agent configuration the Task API does not require mTLS, but always requires authentication.

This would make it much easier when working with an mTLS enabled cluster :innocent: and IIRC only requires a newer version of the Nomad API client.

https://developer.hashicorp.com/nomad/api-docs/task-api
https://github.com/hashicorp/nomad/pull/16872

**Comment by blinkinglight** [comment]
you coul try this build from main branch ghcr.io/ituoga/coredns-nomad:main

**Comment by henrikjohansen** [comment]
@blinkinglight Something seems off,  running the above image I get _unsupported protocol scheme "unix"_ ...

```
service.nomad.:1053
CoreDNS-1.11.3
linux/amd64, go1.21.13, c742ec03f-dirty
[DEBUG] plugin/nomad: Looking up record for svc: dns namespace: default
[ERROR] plugin/nomad: getClientfailed querying self endpoint: Get "unix:///v1/agent/self?namespace=platform®ion=global": unsupported protocol scheme "unix"
[INFO] 172.19.92.116:64739 - 57057 "A IN dns.default.service.nomad. udp 54 false 4096" NOERROR qr,aa,rd 43 0.00034716s
```

The corresponding Corefile  is :

```
service.nomad.:1053 {
    errors
    debug
    health
    log
    nomad {
      zone service.nomad
      address unix:///secrets/api.sock
      ttl 10
    }
}

```

**Comment by apollo13** [comment]
@henrikjohansen Could you try without `address`, and set `NOMAD_ADDR` as env var instead (though I think nomad might do that by default?)

**Comment by apollo13** [comment]
So I just tried this locally via a manually built coredns and it did work, I wonder if something is wonky with the build process so that it fetched the wrong nomad api client?

**Comment by apollo13** [comment]
#5 has a working readme for the task api. I also fixed the Dockerfile so you can easily build this locally and test (till @blinkinglight merged it). I just verified it on a test machine.

**Comment by blinkinglight** [comment]
api.sock requires token . 
token [token]
address unix:///secrets/api.sock 
and it works.

**Comment by apollo13** [comment]
You shouldn't need to specify the token if you use the task file I have added to the readme (it passes the token as env var)

**Comment by blinkinglight** [comment]
that works too. thank you @apollo13
